<?php
/**
 * @package drupal
 * @subpackage droknewsrotator
 * @version 6.x-1.1 May 1, 2010
 * @author RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2010 RocketTheme, LLC
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */
/*====================================
	dRokNewsRotator News Module
====================================*/

/*
* Implementation of hook_block()
*/

function droknewsrotator_block($op = 'list', $delta = 0, $edit = array()) {
	switch ($op) {
	
		case 'list':
			$blocks[0]['info'] = t('dRokNewsRotator');
			$blocks[0]['cache'] = BLOCK_NO_CACHE;
			return $blocks;
			break;
		
		// configure items on block admin page
		case 'configure':
		case 'save':
			break;
		case 'view':

            $block['subject'] = "";
			$block['content'] = theme('droknewsrotator');
			return $block;
			break;
	}

}

function droknewsrotator_theme() {
  return array(
    'droknewsrotator' => array(
      'template' => 'droknewsrotator'
    ),
  );
}


function droknewsrotator_admin() {
	
	$form = array();
	
	$form['droknewsrotator_rotatorCount'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Maximum number of items to retrieve'),
	    '#default_value' => variable_get('droknewsrotator_rotatorCount', 6),
	    '#size' => 4,
	    '#maxlength' => 4,
	    //'#description' => t(""),
	    '#required' => TRUE,
	  );
	  
	  $form['droknewsrotator_delay'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Display Time'),
	    '#default_value' => variable_get('droknewsrotator_delay', 7000),
	    '#size' => 6,
	    '#maxlength' => 6,
	    '#description' => t("Amount of time to display each news item"),
	    '#required' => TRUE,
	  );
	  
	$form['droknewsrotator_duration'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Transition Duration'),
	    '#default_value' => variable_get('droknewsrotator_duration', 800),
	    '#size' => 4,
	    '#maxlength' => 4,
	    '#required' => TRUE,
	  );
	
	$form['droknewsrotator_autoplay'] = array(
	    '#type' => 'select',
	    '#title' => t('Autoplay'),
	    '#options' => array(
			'1' => 'True', 
			'0' => 'False'
		),
	    '#default_value' => variable_get('droknewsrotator_autoplay', 'true'),
	    //'#description' => t(""),
	    '#required' => TRUE,
	  );
	  
	  $form['droknewsrotator_autohide_controls'] = array(
	    '#type' => 'select',
	    '#title' => t('Auto Hide Controls'),
	    '#options' => array(
			'1' => 'True', 
			'0' => 'False'
		),
	    '#default_value' => variable_get('droknewsrotator_autohide_controls', 'true'),
	    //'#description' => t(""),
	    '#required' => TRUE,
	  );
	  
	   $form['droknewsrotator_rotator_controls'] = array(
	    '#type' => 'select',
	    '#title' => t('Rotator Controls'),
	    '#options' => array(
			'1' => 'True', 
			'0' => 'False'
		),
	    '#default_value' => variable_get('droknewsrotator_rotator_controls', 'true'),
	    '#description' => t("Show the rotator control buttons"),
	    '#required' => TRUE,
	  );
	  
	  $form['droknewsrotator_img_path'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Path to Images'),
	    '#default_value' => variable_get('droknewsrotator_img_path', 'files/stories/rotator/'),
	    '#size' => 50,
	    '#maxlength' => 50,
	    '#description' => t("The location of images for dRokNewsRotator"),
	    '#required' => TRUE,
	  );
	  
	  
	  $form['droknewsrotator_preview_length'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Preview Length'),
	    '#default_value' => variable_get('droknewsrotator_preview_length', 300),
	    '#size' => 6,
	    '#maxlength' => 6,
	    '#description' => t("Amount of of preview text to display"),
	    '#required' => TRUE,
	  );
	
	  return system_settings_form($form);
}

function droknewsrotator_menu() {

	$items = array();
	
	$items['admin/rockettheme'] = array(
		'title' => 'RocketTheme',
		'description' => 'Manage settings for custom RocketTheme Modules.',
		'position' => 'right',
		'weight' => -5,
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('administer site configuration'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
	
	);
	
	
	$items['admin/rockettheme/droknewsrotator'] = array(
	'title' => 'dRokNewsRotator ',
	'description' => 'Administer settings for dRokNewsRotator',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('droknewsrotator_admin'),
	'access arguments' => array('access administration pages'),
	'type' => MENU_NORMAL_ITEM,
	);
	
	return $items;
}


